@startuml
(*) --> "具有Push Question权限的角色发布一道题"
--> "具有ANY权限的admin校验题目真实性以及可靠性"
if "审核" then
--> [审核成功] "题目状态更改为pass"
--> (*)
else
--> [审核失败] "填写失败原因,状态更改为reject，出题人可再次提交"
--> "具有ANY权限的admin校验题目真实性以及可靠性"
@enduml