@startuml
(*) --> "获取题目"
if "主动服务号推送" then
--> "用户设置的推送专区（专区爱好）进行范围推送"
--> "获取规则:\n 用户关注的用户最新发布的题优先\n > 当日浏览详情人数最多的优先\n > 当日答题人数最多的题优先"
else
--> [程序中用户进入题目页面获取] "根据用户进入的专区获取题目"
--> "获取规则:\n 用户关注的用户最新发布的题优先\n > 当日浏览详情人数最多的优先\n > 当日答题人数最多的题优先"
Endif
--> "version1: 第三方开源题库 > 自建题库"
--> "越晚时间发布的题目优先"
--> (*)
@enduml