@startuml
(*) --> "是否已微信登录"
if "已经微信登录" then
    if "绑定手机号" then
    --> (*)
    else
    -> "登录(绑定)成功"
    endif
--> (*)
else
-right-> "没有登录"
endif
if "如果选择手机号登录" then
--> "登录(绑定)成功"
else
-right-> "第三方登录"
endif
--> "检查是否绑定了手机号"
--> "登录(绑定)成功"
--> (*)
@enduml